Import('indemic_env', 'libtest_node')

avr_extint_elf = indemic_env.indemicBoardSimAvr(
    'external.at90usb162.avr.elf',
    ['avr-external-at90usb.cpp', 'avr-mcu.c'],
)
Depends(libtest_node, avr_extint_elf)
