Import('cxxtest_env')

test_register = cxxtest_env.CxxTest(
    'test_register',
    [
        'RegisterTest.t.h',
        'RegisterMultiSetterTest.t.h',
        'RegisterVisitorTest.t.h',
        'RegisterDoubleTest.t.h',
    ]
)
