# TODO: check that following files compile with errors:
# RegisterCompileErrorWidthCheckConstructorTest.cpp
# RegisterCompileErrorWidthCheckOperatorTest.cpp
# RegisterCompileErrorWrongRegisterTest.cpp
