Import('cxxtest_env', 'indemicBoard', 'avr_env', 'IndemicBoardBuilder')

avr_sim_env = avr_env.Clone()
avr_sim_env.ParseConfig("pkg-config simavr --cflags")

Export('avr_sim_env')

indemicBoardSimAvr = IndemicBoardBuilder({'avr': avr_sim_env})

Export('indemicBoardSimAvr')

tests_src = [
    'avr/ExternalInterrupt/ExternalInterruptTest.t.h',
    'avr/Timer/PeriodicRunnerTest.t.h',
    'avr/IOPin/IOPinTest.t.h',
    'generic/register/RegisterTest.t.h',
    'generic/register/RegisterMultiSetterTest.t.h',
    'generic/register/RegisterVisitorTest.t.h',
    'generic/register/RegisterDoubleTest.t.h',
]
libtest_node = cxxtest_env.CxxTest('test_lib', tests_src)

Export('libtest_node')

SConscript([ \
    'avr/SConscript', \
    'generic/SConscript', \
])
