Import('at90usb_env', 'cxxtest_env')

avr_output_elf = at90usb_env.Program('avr-output.elf', ['avr-output.cpp', 'avr-mcu.c'])
avr_ddr_elf = at90usb_env.Program('avr-ddr.elf', ['avr-ddr.cpp', 'avr-mcu.c'])

test_iopin = cxxtest_env.CxxTest('test_iopin', ['IOPinTest.h'])

Depends(test_iopin, avr_output_elf)
Depends(test_iopin, avr_ddr_elf)
