Import('at90usb_env', 'libtest_node')

avr_output_elf = at90usb_env.Program('avr-output.elf', ['avr-output.cpp', 'avr-mcu.c'])
Depends(libtest_node, avr_output_elf)

avr_ddr_elf = at90usb_env.Program('avr-ddr.elf', ['avr-ddr.cpp', 'avr-mcu.c'])
Depends(libtest_node, avr_ddr_elf)
